### PR TITLE
Wip auto contributor list for GitHub option

### PR DESCRIPTION
**Pull request by ThT12**
Works fine when creating a new packages.
Does not work properly when regenerate an existing packages (since the position of pkglts marks have moved in AUTHORS.rst and . md). You need to delete the file and regenerate the file again. I didn't find how to avoid that. Any idea?

### CODE REVIEW

**Comment by ThT12** [comment]
There is probably some tests to improve (to mock) since github call requests.get now (that take time)

**Comment by revesansparole** [comment]
Hi,
Great contribution, I should have done it a long time ago :) thanks.

However, you are using github api to generate the list of contributors, which means that each time the package is regenerated there is a call on internet which takes time and might potentially fail simply due to a bad internet connection.

I think a better option would be to stay local using git shortlog command:
https://git-scm.com/docs/git-shortlog
An example is given here:
https://makandracards.com/makandra/15909-quick-git-contributors-list

Open to discussion.

Cheers

**Comment by ThT12** [comment]
I like your solution. I didn't think about using the local repository. I'm going to update the PR.

**Comment by ThT12** [comment]
For some reason
`import subprocess
subprocess.check_output(['git', 'status'])`
works fine, but 
`import subprocess
subprocess.check_output(['git', 'shortlog', '-s'])`
never end. (The command works fine in a git prompt).
So I'm not able to get the contributor list from the git local repo :/ 

Any suggestion ?

**Comment by ThT12** [comment]
Using `git log` and not `git shortlog`.
Works well overall, but get accent and contributor duplication problems.

Still got the "regenerate an existing packages" problem

**Comment by revesansparole** [comment]
contributor duplication can be solved with .mailmap file (pull revesansparole/pkglts for an example)

We'll discuss the "regenerate an existing packages" problem on monday.

**Pull request merged**
